version: '3.8'

services:
  mockplant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mockplant
    ports:
      - "80:80"
    volumes:
      - ./imposters:/app/imposters
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s